FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/prisma ./prisma
COPY --from=deps /app/package.json ./package.json

COPY src ./src

RUN npm run prisma generate

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy && node --import tsx src/server.ts"]