FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/prisma ./prisma
COPY --from=deps /app/package.json ./package.json

COPY src ./src
COPY tsconfig.json ./tsconfig.json
COPY prisma.config.ts ./prisma.config.ts

RUN npx prisma generate

CMD ["node", "--import", "tsx", "src/jobs/worker.ts"]